apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels: #this is deployment labels
    app: cart
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: #this labels will match with the pod
      app: cart
      tier: app
      project: roboshop
  template: #this is the pod def
    metadata:
      labels:
        app: cart
        tier: app
        project: roboshop
    spec:
      containers:
      - name: cart
        image: nishaldevops/cart:1.0.0
        envFrom:
        - configMapRef: 
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
      app: cart
      tier: app
      project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 8080 # this port belongs to service
    targetPort: 8080 # this port belongs to container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: catalogue
  CATALOGUE_PORT: "8080"