apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels: #this is deployment labels
    app: user
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: #this labels will match with the pod
      app: user
      tier: app
      project: roboshop
  template: #this is the pod def
    metadata:
      labels:
        app: user
        tier: app
        project: roboshop
    spec:
      containers:
      - name: user
        image: nishaldevops/user:1.0.0
        envFrom:
        - configMapRef: 
            name: user
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
      app: user
      tier: app
      project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 8080 # this port belongs to service
    targetPort: 8080 # this port belongs to container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
data:
  MONGO: "true" #keep true in double quotes
  REDIS_HOST: "redis"
  MONGO_URL: "mongodb://mongodb:27017/user" #protocol//service-name:service-port/schema
