apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels: #this is deployment labels
    app: redis
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: #this labels will match with the pod
      app: redis
      tier: db
      project: roboshop
  template: #this is the pod def
    metadata:
      labels:
        app: redis
        tier: db
        project: roboshop
    spec:
      containers:
      - name: redis
        image: nishaldevops/redis:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    app: redis
    tier: db
    project: roboshop
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379 # this port belongs to service
    targetPort: 6379 # this port belongs to container